"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Cine_1 = require("./Cine");
const Pelicula_1 = require("./Pelicula");
const Cliente_1 = require("./Cliente");
const cine = Cine_1.Cine.getInstance();
const johnWick4 = new Pelicula_1.Pelicula('John Wick 4');
const transformers = new Pelicula_1.Pelicula('Transformers');
const pikachu = new Pelicula_1.Pelicula('Pikachu');
const volandoAlto = new Pelicula_1.Pelicula('Volando Alto');
const sala1 = cine.crearSala(1, 100, johnWick4, 100);
const sala2 = cine.crearSala(2, 80, transformers, 80);
const sala3 = cine.crearSala(3, 120, pikachu, 120);
const sala4 = cine.crearSala(4, 90, volandoAlto, 90);
const cliente1 = new Cliente_1.Cliente('Juan', johnWick4, sala1, 1, ['Canguil', 'Hot-dog', 'Bebidas']);
const cliente2 = new Cliente_1.Cliente('María', transformers, sala2, 5, ['Canguil', 'Refresco']);
const cliente3 = new Cliente_1.Cliente('Pedro', pikachu, sala3, 10, ['Hot-dog', 'Bebidas']);
const cliente4 = new Cliente_1.Cliente('Laura', volandoAlto, sala4, 15, ['Canguil', 'Refresco']);
cliente1.mostrarDetalle();
cliente2.mostrarDetalle();
cliente3.mostrarDetalle();
cliente4.mostrarDetalle();
